language: cpp

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libx11-dev
      - libxrandr-dev
      - libgl1-mesa-dev
      - libudev-dev
      - libopenal-dev
      - libflac-dev
      - libogg-dev
      - libvorbis-dev

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc

    - name: "macOS Clang Dynamic"
      os: osx
      compiler: clang
      env:
        - CMAKE_FLAGS="-DSFML_DEPENDENCIES_INSTALL_PREFIX=../install"

before_script:
  - if cd SFML; then git pull && cd ..; else git clone https://github.com/SFML/SFML.git; fi
  - ls SFML && cd SFML && mkdir -p build && mkdir -p install && cd build
  - cmake .. $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install
  - cmake --build . --target install
  - cd ../..

script:
  - mkdir build && cd build
  - cmake -DSFML_DIR=../SFML/install/lib/cmake/SFML ..
  - cmake --build .

cache:
  directories:
    - SFML