language: cpp

addons:
  apt_packages:
    - libsfml-dev
    - cmake

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
  - cmake --build .

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc
