language: cpp
addons:
  apt:
    packages:
    - libfreetype6-dev
    - libx11-dev
    - libxrandr-dev
    - libgl1-mesa-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libogg-dev
    - libvorbis-dev
matrix:
  include:
  - name: Linux gcc Dynamic
    os: linux
    dist: xenial
    compiler: gcc
  - name: macOS Clang Dynamic
    os: osx
    compiler: clang
    env:
    - CMAKE_FLAGS="-DSFML_DEPENDENCIES_INSTALL_PREFIX=../SFML-install"
before_script:
- git -C $HOME/SFML pull || git clone https://github.com/SFML/SFML.git $HOME/SFML
- mkdir -p SFML-build && mkdir -p SFML-install && cd SFML-build
- cmake $HOME/SFML $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../SFML-install
- cmake --build . --target install
- cd ..
script:
- mkdir build && cd build
- cmake -DSFML_DIR=$TRAVIS_BUILD_DIR/SFML-install/lib/cmake/SFML ..
- cmake --build .
- cd ..
cache:
  directories:
  - SFML-build
  - SFML-install
  - "$HOME/SFML"
before_deploy:
- zip -r artifacts.zip SFML-build
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
