language: cpp

addons:
  apt_packages:
    - libsfml-dev

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc
