language: cpp

addons:
  apt_packages:
    - cmake

script:
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - tar xzvf SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSFML_DIR=../SFML-2.5.1
  - cmake --build .

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc
