language: cpp

script:
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - tar xzvf SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - mkdir build && cd build
  - ls $HOME/SFML-2.5.1/lib/cmake/SFML
  - cmake -DSFML_DIR=$HOME/SFML-2.5.1/lib/cmake/SFML ..
  - cmake --build .

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc
