language: cpp

script:
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - tar xzvf SFML-2.5.1-linux-gcc-64-bit.tar.gz
  - pwd
  - ls
  - mkdir build && cd build
  - ls $HOME/build/SamuelGallay/BrownianMotion/SFML-2.5.1/lib/cmake/SFML
  - cmake -DSFML_DIR=$HOME/build/SamuelGallay/BrownianMotion/SFML-2.5.1 ..
  - cmake --build .

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc
