language: cpp

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libx11-dev
      - libxrandr-dev
      - libgl1-mesa-dev
      - libudev-dev
      - libopenal-dev
      - libflac-dev
      - libogg-dev
      - libvorbis-dev

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc

    - name: "macOS Clang Dynamic"
      os: osx
      compiler: clang
      env:
        - CMAKE_FLAGS="-DSFML_DEPENDENCIES_INSTALL_PREFIX=../SFML-install"

before_script:
  - git clone https://github.com/SFML/SFML.git
  - mkdir -p SFML-build && mkdir -p SFML-install && cd SFML-build
  - cmake ../SFML $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../SFML-install
  - cmake --build . --target install
  - cd ..

script:
  - mkdir build && cd build
  - cmake -DSFML_DIR=$TRAVIS_BUILD_DIR/SFML-install/lib/cmake/SFML ..
  - cmake --build .

cache:
  directories:
    - SFML-build
    - SFML-install