language: cpp

matrix:
  include:

    - name: "Linux gcc Dynamic"
      os: linux
      dist: xenial
      compiler: gcc
      script:
        - wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
        - tar xzvf SFML-2.5.1-linux-gcc-64-bit.tar.gz
        - mkdir build && cd build
        - cmake -DSFML_DIR=$HOME/build/SamuelGallay/BrownianMotion/SFML-2.5.1/lib/cmake/SFML ..
        - cmake --build .

    - name: "macOS Clang Dynamic"
      os: osx
      compiler: clang
      script:
        - wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
        - unzip -n SFML-2.5.1-sources.zip
        - cd SFML-2.5.1
        - mkdir build
        - mkdir install
        - cd build
        - cmake -DCMAKE_INSTALL_PREFIX=../install ..
        - sudo make install
        - cd ../..
        - mkdir build && cd build
        - cmake -DSFML_DIR=$HOME/build/SamuelGallay/BrownianMotion/SFML-2.5.1/lib/cmake/SFML ..
        - cmake --build .
      cache:
        directories:
          - SFML-2.5.1
